// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package sim

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[title-0]
	_ = x[subtitle-1]
	_ = x[integer-2]
	_ = x[float-3]
	_ = x[vec2-4]
}

const _TokenType_name = "titlesubtitleintegerfloatvec2"

var _TokenType_index = [...]uint8{0, 5, 13, 20, 25, 29}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
